### ISSUE TITLE
Markdown fences render ${{}} incorrectly

### ISSUE THREAD

**Issue by jenshor** [invertase/docs.page#215]
I'm currently trying to render a markdown which contains `${{ <some text> }}` like this:

**The markdown**

````
```yaml
${{ test }}
```
````

**What i'm expecting**
```yaml
${{ test }}
```

**What it looks like**
```yaml
$
```

**What it looks like (screenshot)**
<img width="859" alt="image" src="https://user-images.githubusercontent.com/16862002/173515252-57cea113-f7f3-44eb-8c7b-3b8a874a4115.png">

Am i doing something wrong? Is there a way to escape this? 
I tried to solve this but i'm not really sure whats the exact problem. Just looks like the text within the brackets is interpreted in some way.

Found something about Jekyll interpreting these values but I'm not even sure if thats used in the background.

Let me know if I can help with additional information.
Appreciate your work and your help 👍🏻

**Comment by cabljac** [comment]
I'll check this out :) Thanks for raising this!

**Comment by JensHor** [comment]
Thanks for looking into this 👍🏻

In addition, i've tried to put `${{ test }}` as plain text without any fences and I think this will straight up return a `500` whenever a page with such content is accessed (but i'm not sure.)

Unfortunately I cannot go into detail on whats happening because i cannot read any helpful information from the console. If you like you can try yourself here: [https://docs.widgetbook.io/widgetbook-cloud/review](https://docs.widgetbook.io/widgetbook-cloud/review)

**Comment by cabljac** [comment]
I figured out why it's being remove at least, our global variable feature was replacing even if the variable isn't defined. I fixed that, but i'll make sure it doesn't 500 too.

Also on my list is to make errors more useful on client side/ add a debug page :D just haven't had much time for it recently

**Comment by cabljac** [comment]
OK so i have a fix for the fenced version, and I think i know what's happening in the non-fenced version. I have a workaround for the non-fenced version. I think it's down to mdx there. I'll get the fix for the fenced version merged in ASAP.

the workaround is that when you want {{ test }} (non-fenced by a code block) you can escape like this \{\{ test \}\}|

What i think is happening is that mdx interprets this as a reference to a variable `test`, which isn't declared in the mdx.

**Comment by cabljac** [comment]
OK it seems like the unfenced issue is down to MDX as i suspected, I will have to think about the best way to handle that.

<img width="1121" alt="Screenshot 2022-06-16 at 13 59 27" src="https://user-images.githubusercontent.com/32874567/174075076-ade6e546-7fa2-4ada-ba01-d5bfe356a0d6.png">

**Comment by JensHor** [comment]
Tested this recently and the page no longer goes to 500, when the described code is used outside of fences. However, within fences this still not works. Just letting you know 😉

Any ETA on this?

**Comment by JensHor** [comment]
@cabljac in addition, is there a way to contact you for a private feature request? I don't see an option to contact you on GitHub and you seem not to accept messages on Twitter as well. I have total understanding if you don't want to be contacted but it would be great if I could shoot you a private message.

If you don't want to disclose your information publicly but would like to get in touch just shoot me a short email or a DM via twitter.

Thanks in advance.

**Comment by jenshor** [comment]
I also found something that seem to be related to this issue:

code like `checkout@v2` is replaced by `[email protected]`.

**Example:**

```yaml
name: Build 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/[email protected]
```

**What I expect:**
```yaml
name: Build 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
```

**Comment by cabljac** [comment]
Hi, sorry - been taken up on other projects recently and just come back from vacation. I will look into this asap!

**Comment by cabljac** [comment]
Hey, I have a PR waiting to be merged still, which i think fixed this issue. I have to go back and test/review it, will hopefully do this today.

**Comment by cabljac** [comment]
Hey I've merged that PR in, I think it's fixed this issue, e.g https://docs.page/cabljac/test/test

let me know if there's still something going wrong

**Comment by cabljac** [comment]
I'm going to close this issue as I think it's solved. Let me know if not and i can reopen :D
